name: "Test"
on:
  push:
env:
  # This is for the benefit of nix-shell, as we do not
  # have a NIXPATH nixpkgs configured
  NIX_BUILD_SHELL: /bin/bash
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
    - name: Add kaleidogen cachix
      uses: cachix/cachix-action@v12
      with:
        name: kaleidogen
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    # until https://github.com/cachix/cachix-action/issues/86 is fixed:
    - run: cachix watch-store kaleidogen &

    - name: Prepare nix shell
      run: nix-build --no-out-link shell.nix


    - name: Build all
      run: nix-shell --pure --command make

    - name: Run tests
      run: nix-shell --pure --command "make test"

    - name: Deploy
      run: ./deploy.sh _out

    - name: Deploy to Github Pages
      if: github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        branch: gh-pages
        folder: _out
        single-commit: true
